# Dockerfile para a aplicação Flask
FROM python:3.8-slim

# Define o diretório de trabalho
WORKDIR /app

# Instala as dependências necessárias
RUN apt-get update && \
    apt-get install -y poppler-utils ghostscript && \
    apt-get clean

# Copia os arquivos necessários para o contêiner
COPY requirements.txt requirements.txt
COPY app.py app.py
COPY reducers.py reducers.py
COPY converts.py converts.py
COPY log_service.py log_service.py
COPY templates templates

# Cria o diretório de uploads
RUN mkdir -p /tmp/uploads

# Instala as dependências do Python
RUN pip install --no-cache-dir -r requirements.txt

# Comando para rodar a aplicação
CMD ["python", "app.py"]
